// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtjdjicaivzabecnqnxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0amRqaWNhaXZ6YWJlY25xbnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDE5OTMsImV4cCI6MjA2OTkxNzk5M30.uDF-EdNXLxLBSAd48Nz2-C-MpDzKsUGz42olfjQrfQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});